"""
Backstage realtime ranking scraper.

Strategy:
1. Load saved session (storage_state.json)
2. Open revenue/task page (msToken/X-Bogus/X-Gnarly auto-generated by page JS)
3. Call get_anchor_settle_detail_v2 via page.evaluate fetch (in-page context)
   — this lets Backstage JSSDK auto-add security tokens
4. Paginate 100 × 8 for all 768 creators
5. Output JSON with rank / nickname / username / diamonds / last month / isLive / manager etc.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import List, Dict, Tuple, Optional

from playwright.sync_api import sync_playwright

BASE = Path(__file__).parent
STORAGE = BASE / "storage_state.json"
OUT_DIR = Path(os.environ.get("OUTPUT_DIR", BASE))
OUT_INTERNAL = OUT_DIR / "ranking_realtime_internal.json"
OUT_LIVERS = OUT_DIR / "ranking_realtime_livers.json"

WORKSPACE_URL = "https://live-backstage.tiktok.com/portal/workspace/"
REVENUE_URL_TMPL = "https://live-backstage.tiktok.com/portal/revenue/task?Month={month}&viewTab=by_creator"
API_PATH = "/creators/live/union_platform_api/agency/task/get_anchor_settle_detail_v2/"

# Filtering rules (aligned with existing livers.html)
EXCLUDED_USERS = {"minomomo0219"}
LIVERS_TOP_N = 20

# API returns manager ID as email prefix (e.g. "yuki.sazanami" from yuki.sazanami@bcode.co.jp)
# Map prefix → display name (subset of existing MANAGER_NAMES from generate_ranking.py)
MANAGER_BY_PREFIX = {
    "katsuaki.takizawa.bcode": "Katsu",
    "info": "Katsu",  # info@sinceed.co.jp
    "katsuaki.takizawa.grove": "Katsu",
    "katsuaki.takizawa": "Katsu",
    "tomoki.imanishi.bcode": "今西",
    "hiroki.tanaka.bcode": "田中",
    "haruno.tsutsumi.bcode": "堤",
    "yuki.sazanami": "漣",
    "nf_sdc15.1130": "NF",
    "tsuyoshi.takahashi.bcode": "高橋",
}

# After mapping, these names are "internal managers" shown on the livers page
MANAGER_DISPLAY = {"Katsu": "滝澤", "NF": "田山"}  # to convert to display-friendly
INTERNAL_MANAGERS = {"漣", "今西", "田中", "堤", "田山", "高橋", "滝澤"}

JST = timezone(timedelta(hours=9))


def current_month_yyyymm() -> str:
    return datetime.now(JST).strftime("%Y%m")


def fetch_settle_sub_job_id(page, month: str) -> str:
    """Navigate revenue page, wait for Backstage's own first XHR (interceptors live by then),
    scrape SettleSubJobID from the URL query."""
    url = REVENUE_URL_TMPL.format(month=month)

    # Wait for Backstage to make its own detail request — this confirms interceptors are initialized
    with page.expect_response(
        lambda r: "get_anchor_settle_detail_v2" in r.url and r.status == 200,
        timeout=30000,
    ):
        page.goto(url, wait_until="domcontentloaded")
        page.wait_for_url(lambda u: "SettleSubJobID=" in u, timeout=15000)

    from urllib.parse import urlparse, parse_qs
    qs = parse_qs(urlparse(page.url).query)
    sub_job_id = qs.get("SettleSubJobID", [None])[0]
    if not sub_job_id:
        raise RuntimeError(f"SettleSubJobID not found in URL: {page.url}")
    return sub_job_id


def fetch_all_by_ui(page) -> Tuple[list, dict]:
    """Drive the UI to paginate. page.evaluate-triggered XHRs are blocked by bot protection,
    but UI-driven clicks pass through. Collect all matching responses via page.on('response')."""
    collected: List[dict] = []

    def on_response(resp):
        if "get_anchor_settle_detail_v2" in resp.url:
            print(f"[on_response] status={resp.status} url_tail=…{resp.url[-120:]}")
            if resp.status == 200:
                try:
                    data = resp.json()
                    sc = data.get("BaseResp", {}).get("StatusCode")
                    details = len(data.get("DetailList") or [])
                    print(f"[on_response] sc={sc} limit={data.get('Limit')} offset={data.get('Offset')} total={data.get('Total')} detailCount={details}")
                    if sc == 0 and details > 0:
                        collected.append(data)
                except Exception as e:
                    print(f"[on_response] parse err: {e}")

    page.on("response", on_response)

    def has_offset(off: int) -> bool:
        return any(c.get("Limit") == 100 and c.get("Offset") == off for c in collected)

    def wait_for_offset(off: int, timeout_sec: float = 20.0) -> bool:
        elapsed = 0.0
        step = 0.3
        while elapsed < timeout_sec:
            time.sleep(step)
            elapsed += step
            if has_offset(off):
                return True
        return False

    # Open page size dropdown (Semi UI combobox) and select 100
    print("[ui] opening page size dropdown…")
    page.locator(".semi-page-switch .semi-select").click(timeout=15000)
    time.sleep(1.0)
    print("[ui] selecting 100 per page…")
    page.get_by_role("option", name="1ページあたりのアイテム数：100").click(timeout=10000)
    time.sleep(2)

    # Click Next once to reliably apply Limit=100 (observed behavior: Limit takes effect
    # on the next navigation action, not on the select itself)
    page.locator('li.semi-page-next[aria-label="Next"]').click(timeout=10000)
    if not wait_for_offset(0, timeout_sec=15):
        raise RuntimeError("Failed to get page 1 at Limit=100")

    total = next(c["Total"] for c in collected if c.get("Limit") == 100)
    expected_pages = (total + 99) // 100
    print(f"[ui] total={total}, pages to navigate: {expected_pages}")

    # Click each page number directly (aria-label="Page N")
    for page_num in range(2, expected_pages + 1):
        offset = (page_num - 1) * 100
        if has_offset(offset):
            continue
        selector = f'li.semi-page-item[aria-label="Page {page_num}"]'
        try:
            page.locator(selector).click(timeout=8000)
            if wait_for_offset(offset, timeout_sec=15):
                print(f"[ui] page {page_num} (offset={offset}): ✓")
            else:
                print(f"[ui] page {page_num}: timeout (retrying via Next)")
                try:
                    page.locator('li.semi-page-next[aria-label="Next"]').click(timeout=5000)
                    wait_for_offset(offset, timeout_sec=15)
                except Exception:
                    pass
        except Exception as e:
            print(f"[ui] page {page_num}: click failed ({e})")

    # Final wait for any missing pages (in case responses are still in flight)
    for page_num in range(1, expected_pages + 1):
        offset = (page_num - 1) * 100
        if not has_offset(offset):
            print(f"[ui] final wait for offset={offset}…")
            wait_for_offset(offset, timeout_sec=20)

    # Merge de-duplicated (by offset)
    by_offset = {c["Offset"]: c for c in collected if c.get("Limit") == 100}
    all_details = []
    all_infos = {}
    for offset in sorted(by_offset):
        all_details.extend(by_offset[offset].get("DetailList", []))
        all_infos.update(by_offset[offset].get("HostBaseInfoMap", {}))

    return all_details, all_infos


def build_records(details: list, infos: dict) -> list:
    """Merge detail + info, compute rank by TotalDiamonds desc."""
    records = []
    for d in details:
        anchor_id = d.get("AnchorID")
        info = infos.get(anchor_id, {})
        manager = d.get("GroupManagerName") or d.get("AgentName") or ""
        records.append({
            "anchorId": anchor_id,
            "nickname": info.get("nickname", ""),
            "username": info.get("display_id", ""),
            "avatar": info.get("avatar", ""),
            "isLive": info.get("IsLive", False),
            "totalDiamonds": int(d.get("TotalDiamonds", 0) or 0),
            "lastMonthDiamonds": int(d.get("LastMonthTotalDiamonds", 0) or 0),
            "pkDiamondsMtd": int(d.get("PkIncomeDiamondMtd", 0) or 0),
            "broadcastDays": d.get("BroadcastDays", 0),
            "broadcastDurationSec": d.get("BroadcastDuration", 0),
            "contributionBonusUSD": d.get("ContributionBonusUSD", 0),
            "lastMonthContributionBonusUSD": d.get("LastMonthContributionBonusUSD", 0),
            "group": d.get("GroupName", ""),
            "manager": manager,
            "managerRaw": d.get("GroupManagerName", ""),
            "agent": d.get("AgentName", ""),
            "isCurrentAgency": d.get("IsCurrentAgencyAnchor", False),
        })

    records.sort(key=lambda r: (-r["totalDiamonds"], r["username"]))
    for i, r in enumerate(records):
        r["rank"] = i + 1
    return records


def display_manager(manager_raw: str) -> Optional[str]:
    """API manager field → display name if internal; None if not internal."""
    if not manager_raw:
        return None
    # API gives email prefix (before @). Map to known name, then to display form.
    name = MANAGER_BY_PREFIX.get(manager_raw, manager_raw)
    name = MANAGER_DISPLAY.get(name, name)
    return name if name in INTERNAL_MANAGERS else None


def build_internal_json(records: list, updated_at: str) -> dict:
    """All creators (filtered to active agency), with manager info."""
    filtered = [
        {**r, "managerDisplay": display_manager(r["manager"])}
        for r in records
        if r["isCurrentAgency"]
        and r["username"] not in EXCLUDED_USERS
    ]
    return {
        "generatedAt": updated_at,
        "totalCount": len(filtered),
        "activeCount": sum(1 for r in filtered if r["totalDiamonds"] > 0),
        "liveNow": sum(1 for r in filtered if r["isLive"]),
        "creators": filtered,
    }


def build_livers_json(records: list, updated_at: str) -> dict:
    """Top N visible to livers — only creators with internal manager, excluded users removed.
    Renumbers ranks 1..N within the filtered subset (displayRank) while preserving global rank."""
    filtered = [
        r for r in records
        if r["isCurrentAgency"]
        and r["username"] not in EXCLUDED_USERS
        and display_manager(r["manager"]) is not None
    ]
    top_n = filtered[:LIVERS_TOP_N]
    for i, r in enumerate(top_n):
        r["displayRank"] = i + 1
    return {
        "generatedAt": updated_at,
        "topN": LIVERS_TOP_N,
        "creators": top_n,
    }


def main():
    if not STORAGE.exists():
        print(f"❌ セッションファイルがありません: {STORAGE}")
        print("先に `python3 login.py` を実行してください")
        sys.exit(1)

    headless_env = os.environ.get("HEADLESS", "1")
    headless = headless_env != "0"

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=headless)
        context = browser.new_context(storage_state=str(STORAGE), locale="ja-JP")
        page = context.new_page()

        month = current_month_yyyymm()
        print(f"[scrape] month={month}, fetching SettleSubJobID…")
        sub_job_id = fetch_settle_sub_job_id(page, month)
        print(f"[scrape] SettleSubJobID={sub_job_id}")

        details, infos = fetch_all_by_ui(page)
        print(f"[scrape] fetched {len(details)} creators")

        records = build_records(details, infos)
        updated_at = datetime.now(JST).isoformat(timespec="seconds")

        internal = build_internal_json(records, updated_at)
        livers = build_livers_json(records, updated_at)

        OUT_DIR.mkdir(parents=True, exist_ok=True)
        OUT_INTERNAL.write_text(json.dumps(internal, ensure_ascii=False, indent=2))
        OUT_LIVERS.write_text(json.dumps(livers, ensure_ascii=False, indent=2))
        print(f"[scrape] wrote {OUT_INTERNAL.name} ({internal['totalCount']} creators, {internal['liveNow']} live)")
        print(f"[scrape] wrote {OUT_LIVERS.name} (top {len(livers['creators'])})")

        # Refresh storage in case cookies rotated
        context.storage_state(path=str(STORAGE))
        browser.close()


if __name__ == "__main__":
    main()
