"""
Backstage realtime ranking scraper.

Strategy:
1. Load saved session (storage_state.json)
2. Open revenue/task page (msToken/X-Bogus/X-Gnarly auto-generated by page JS)
3. Call get_anchor_settle_detail_v2 via page.evaluate fetch (in-page context)
   — this lets Backstage JSSDK auto-add security tokens
4. Paginate 100 × 8 for all 768 creators
5. Output JSON with rank / nickname / username / diamonds / last month / isLive / manager etc.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import List, Dict, Tuple, Optional

from playwright.sync_api import sync_playwright

BASE = Path(__file__).parent
OUT_DIR = Path(os.environ.get("OUTPUT_DIR", BASE))
# Latest files (always current month)
OUT_INTERNAL = OUT_DIR / "ranking_realtime_internal.json"
OUT_LIVERS = OUT_DIR / "ranking_realtime_livers.json"
# Per-month archives written alongside. Once a month rolls over, its file freezes
# (scraper starts writing to the new month's file) → historical snapshot preserved.
def archive_path(prefix: str, yyyymm: str) -> Path:
    return OUT_DIR / f"{prefix}_{yyyymm}.json"

# Agencies to scrape — each with its own Backstage session file.
# Alpha=101020 (bcode), Ulysses=100712 (grove). Add more here if needed.
AGENCIES = [
    ("alpha", BASE / "storage_state.json"),
    ("ulysses", BASE / "storage_state_ulysses.json"),
]

WORKSPACE_URL = "https://live-backstage.tiktok.com/portal/workspace/"
# アクティブ度インセンティブ task view — this lens populates BroadcastDuration (hours).
# The default overview view returns BroadcastDuration=0. TaskID is stable across months.
ACTIVITY_TASK_ID = "7610716343062757387"
REVENUE_URL_TMPL = f"https://live-backstage.tiktok.com/portal/revenue/task?Month={{month}}&TaskID={ACTIVITY_TASK_ID}&subViewTab=EligibleAnchor&viewTab=by_creator"
API_PATH = "/creators/live/union_platform_api/agency/task/get_anchor_settle_detail_v2/"

# Filtering rules (aligned with existing livers.html)
EXCLUDED_USERS = {"minomomo0219"}
LIVERS_TOP_N = 20

# API returns manager ID as email prefix (e.g. "yuki.sazanami" from yuki.sazanami@bcode.co.jp)
# Map prefix → display name (subset of existing MANAGER_NAMES from generate_ranking.py)
MANAGER_BY_PREFIX = {
    "katsuaki.takizawa.bcode": "Katsu",
    "info": "Katsu",  # info@sinceed.co.jp
    "katsuaki.takizawa.grove": "Katsu",
    "katsuaki.takizawa": "Katsu",
    "tomoki.imanishi.bcode": "今西",
    "hiroki.tanaka.bcode": "田中",
    "haruno.tsutsumi.bcode": "堤",
    "yuki.sazanami": "漣",
    "nf_sdc15.1130": "NF",
    "tsuyoshi.takahashi.bcode": "高橋",
}

# After mapping, these names are "internal managers" shown on the livers page
MANAGER_DISPLAY = {"Katsu": "滝澤", "NF": "田山"}  # to convert to display-friendly
INTERNAL_MANAGERS = {"漣", "今西", "田中", "堤", "田山", "高橋", "滝澤"}

JST = timezone(timedelta(hours=9))


def current_month_yyyymm() -> str:
    return datetime.now(JST).strftime("%Y%m")


def fetch_settle_sub_job_id(page, month: str) -> str:
    """Navigate revenue page, wait for Backstage's own first XHR (interceptors live by then),
    scrape SettleSubJobID from the URL query."""
    url = REVENUE_URL_TMPL.format(month=month)

    # Wait for Backstage to make its own detail request — this confirms interceptors are initialized
    with page.expect_response(
        lambda r: "get_anchor_settle_detail_v2" in r.url and r.status == 200,
        timeout=60000,
    ):
        page.goto(url, wait_until="domcontentloaded")
        page.wait_for_url(lambda u: "SettleSubJobID=" in u, timeout=30000)

    from urllib.parse import urlparse, parse_qs
    qs = parse_qs(urlparse(page.url).query)
    sub_job_id = qs.get("SettleSubJobID", [None])[0]
    if not sub_job_id:
        raise RuntimeError(f"SettleSubJobID not found in URL: {page.url}")
    return sub_job_id


def fetch_all_by_ui(page) -> Tuple[list, dict]:
    """Drive the UI to paginate. page.evaluate-triggered XHRs are blocked by bot protection,
    but UI-driven clicks pass through. Collect all matching responses via page.on('response')."""
    collected: List[dict] = []

    def on_response(resp):
        if "get_anchor_settle_detail_v2" in resp.url:
            print(f"[on_response] status={resp.status} url_tail=…{resp.url[-120:]}")
            if resp.status == 200:
                try:
                    data = resp.json()
                    sc = data.get("BaseResp", {}).get("StatusCode")
                    details = len(data.get("DetailList") or [])
                    print(f"[on_response] sc={sc} limit={data.get('Limit')} offset={data.get('Offset')} total={data.get('Total')} detailCount={details}")
                    if sc == 0 and details > 0:
                        collected.append(data)
                except Exception as e:
                    print(f"[on_response] parse err: {e}")

    page.on("response", on_response)

    def has_offset(off: int) -> bool:
        return any(c.get("Limit") == 100 and c.get("Offset") == off for c in collected)

    def wait_for_offset(off: int, timeout_sec: float = 20.0) -> bool:
        elapsed = 0.0
        step = 0.3
        while elapsed < timeout_sec:
            time.sleep(step)
            elapsed += step
            if has_offset(off):
                return True
        return False

    # Open page size dropdown (Semi UI combobox) and select 100
    print("[ui] opening page size dropdown…")
    page.locator(".semi-page-switch .semi-select").click(timeout=15000)
    time.sleep(1.0)
    print("[ui] selecting 100 per page…")
    page.get_by_role("option", name="1ページあたりのアイテム数：100").click(timeout=10000)
    time.sleep(3)

    # Click Next once to reliably apply Limit=100 (observed behavior: Limit takes effect
    # on the next navigation action, not on the select itself).
    # Retry because on some views the Next button takes longer to become clickable.
    for attempt in range(3):
        try:
            page.locator('li.semi-page-next[aria-label="Next"]:not([aria-disabled="true"])').click(timeout=10000)
            break
        except Exception as e:
            if attempt == 2:
                raise
            print(f"[ui] Next click attempt {attempt+1} failed, retrying…")
            time.sleep(2)
    if not wait_for_offset(0, timeout_sec=20):
        raise RuntimeError("Failed to get page 1 at Limit=100")

    total = next(c["Total"] for c in collected if c.get("Limit") == 100)
    expected_pages = (total + 99) // 100
    print(f"[ui] total={total}, pages to navigate: {expected_pages}")

    # Click each page number directly (aria-label="Page N")
    for page_num in range(2, expected_pages + 1):
        offset = (page_num - 1) * 100
        if has_offset(offset):
            continue
        selector = f'li.semi-page-item[aria-label="Page {page_num}"]'
        try:
            page.locator(selector).click(timeout=8000)
            if wait_for_offset(offset, timeout_sec=15):
                print(f"[ui] page {page_num} (offset={offset}): ✓")
            else:
                print(f"[ui] page {page_num}: timeout (retrying via Next)")
                try:
                    page.locator('li.semi-page-next[aria-label="Next"]').click(timeout=5000)
                    wait_for_offset(offset, timeout_sec=15)
                except Exception:
                    pass
        except Exception as e:
            print(f"[ui] page {page_num}: click failed ({e})")

    # Final wait for any missing pages (in case responses are still in flight)
    for page_num in range(1, expected_pages + 1):
        offset = (page_num - 1) * 100
        if not has_offset(offset):
            print(f"[ui] final wait for offset={offset}…")
            wait_for_offset(offset, timeout_sec=20)

    # Merge de-duplicated (by offset)
    by_offset = {c["Offset"]: c for c in collected if c.get("Limit") == 100}
    all_details = []
    all_infos = {}
    for offset in sorted(by_offset):
        all_details.extend(by_offset[offset].get("DetailList", []))
        all_infos.update(by_offset[offset].get("HostBaseInfoMap", {}))

    return all_details, all_infos


SCRAPER_TO_SOURCE = {"alpha": "アルファ", "ulysses": "ユリシス"}


def build_records(details: list, infos: dict) -> list:
    """Merge detail + info, dedupe by AnchorID, compute rank by TotalDiamonds desc."""
    by_id: dict = {}
    for d in details:
        aid = d.get("AnchorID")
        if not aid:
            continue
        prev = by_id.get(aid)
        if prev is None or (d.get("IsCurrentAgencyAnchor") and not prev.get("IsCurrentAgencyAnchor")):
            by_id[aid] = d
    details = list(by_id.values())

    records = []
    for d in details:
        anchor_id = d.get("AnchorID")
        info = infos.get(anchor_id, {})
        # AgentName = agency-level assignment (use for internal-manager filtering)
        # GroupManagerName = sub-group leader (often external like HIKE's m.kagami)
        manager = d.get("AgentName") or d.get("GroupManagerName") or ""
        scraper_agency = d.get("_scraperAgency", "")
        records.append({
            "anchorId": anchor_id,
            "nickname": info.get("nickname", ""),
            "username": info.get("display_id", ""),
            "avatar": info.get("avatar", ""),
            "isLive": info.get("IsLive", False),
            "totalDiamonds": int(d.get("TotalDiamonds", 0) or 0),
            "lastMonthDiamonds": int(d.get("LastMonthTotalDiamonds", 0) or 0),
            "pkDiamondsMtd": int(d.get("PkIncomeDiamondMtd", 0) or 0),
            "broadcastDays": d.get("BroadcastDays", 0),
            "broadcastDurationHours": d.get("BroadcastDuration", 0),
            "contributionBonusUSD": d.get("ContributionBonusUSD", 0),
            "lastMonthContributionBonusUSD": d.get("LastMonthContributionBonusUSD", 0),
            "group": d.get("GroupName", ""),
            "manager": manager,
            "managerRaw": d.get("GroupManagerName", ""),
            "agent": d.get("AgentName", ""),
            "source": SCRAPER_TO_SOURCE.get(scraper_agency, scraper_agency),
            "isCurrentAgency": d.get("IsCurrentAgencyAnchor", False),
        })

    records.sort(key=lambda r: (-r["totalDiamonds"], r["username"]))
    for i, r in enumerate(records):
        r["rank"] = i + 1
    return records


def display_manager(manager_raw: str) -> Optional[str]:
    """API manager field → display name if internal; None if not internal."""
    if not manager_raw:
        return None
    # API gives email prefix (before @). Map to known name, then to display form.
    name = MANAGER_BY_PREFIX.get(manager_raw, manager_raw)
    name = MANAGER_DISPLAY.get(name, name)
    return name if name in INTERNAL_MANAGERS else None


def build_internal_json(records: list, updated_at: str) -> dict:
    """All creators (filtered to active agency), with manager info."""
    filtered = [
        {**r, "managerDisplay": display_manager(r["manager"])}
        for r in records
        if r["isCurrentAgency"]
        and r["username"] not in EXCLUDED_USERS
    ]
    return {
        "generatedAt": updated_at,
        "totalCount": len(filtered),
        "activeCount": sum(1 for r in filtered if r["totalDiamonds"] > 0),
        "liveNow": sum(1 for r in filtered if r["isLive"]),
        "creators": filtered,
    }


def build_livers_json(records: list, updated_at: str) -> dict:
    """Top N visible to livers — only creators with internal manager, excluded users removed.
    Renumbers ranks 1..N within the filtered subset (displayRank) while preserving global rank."""
    filtered = [
        r for r in records
        if r["isCurrentAgency"]
        and r["username"] not in EXCLUDED_USERS
        and display_manager(r["manager"]) is not None
    ]
    top_n = filtered[:LIVERS_TOP_N]
    for i, r in enumerate(top_n):
        r["displayRank"] = i + 1
    return {
        "generatedAt": updated_at,
        "topN": LIVERS_TOP_N,
        "creators": top_n,
    }


def scrape_one_agency(p, name: str, storage_path: Path, headless: bool) -> Tuple[list, dict]:
    """Launch browser with the given session, fetch all creators for that agency.
    Returns (details, infos). Refreshes storage file to keep cookies alive.
    Tags each detail with _scraperAgency since AgencyID isn't in this API response."""
    browser = p.chromium.launch(headless=headless)
    context = browser.new_context(storage_state=str(storage_path), locale="ja-JP")
    page = context.new_page()
    try:
        month = current_month_yyyymm()
        print(f"[{name}] month={month}, fetching SettleSubJobID…")
        sub_job_id = fetch_settle_sub_job_id(page, month)
        print(f"[{name}] SettleSubJobID={sub_job_id}")
        details, infos = fetch_all_by_ui(page)
        for d in details:
            d["_scraperAgency"] = name
        print(f"[{name}] fetched {len(details)} creators")
        context.storage_state(path=str(storage_path))
        return details, infos
    finally:
        browser.close()


def main():
    available = [(name, path) for name, path in AGENCIES if path.exists()]
    if not available:
        print(f"❌ セッションファイルが1つもありません")
        print(f"先に `python3 login.py` を実行してください（bcodeでログイン）")
        sys.exit(1)

    print(f"[main] scraping {len(available)} agencies: {[n for n, _ in available]}")

    headless_env = os.environ.get("HEADLESS", "1")
    headless = headless_env != "0"

    all_details = []
    all_infos: dict = {}

    with sync_playwright() as p:
        for name, path in available:
            try:
                details, infos = scrape_one_agency(p, name, path, headless)
                all_details.extend(details)
                all_infos.update(infos)
            except Exception as e:
                print(f"[{name}] ERROR: {e}")
                # Don't abort — other agencies may still succeed
                if len(available) == 1:
                    raise

    print(f"[main] total {len(all_details)} creators across {len(available)} agencies")

    records = build_records(all_details, all_infos)
    updated_at = datetime.now(JST).isoformat(timespec="seconds")

    internal = build_internal_json(records, updated_at)
    livers = build_livers_json(records, updated_at)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    month = current_month_yyyymm()
    write_internal = os.environ.get("OUTPUT_INTERNAL", "1") != "0"

    internal_str = json.dumps(internal, ensure_ascii=False, indent=2)
    livers_str = json.dumps(livers, ensure_ascii=False, indent=2)

    if write_internal:
        OUT_INTERNAL.write_text(internal_str)
        archive_path("ranking_realtime_internal", month).write_text(internal_str)
        print(f"[main] wrote internal ({internal['totalCount']} creators, {internal['liveNow']} live) + archive {month}")
    else:
        print(f"[main] skipped internal (OUTPUT_INTERNAL=0): would be {internal['totalCount']} creators, {internal['liveNow']} live")

    OUT_LIVERS.write_text(livers_str)
    archive_path("ranking_realtime_livers", month).write_text(livers_str)
    print(f"[main] wrote livers (top {len(livers['creators'])}) + archive {month}")


if __name__ == "__main__":
    main()
